import React from 'react';
import { ShieldAlert, Activity, HeartPulse, ClipboardCheck, Info, CheckCircle2 } from 'lucide-react';

// Helper for the User Icon
const UserIcon = ({ size }) => <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>;

const MedicalReportTemplate = React.forwardRef(({ result, formData }, ref) => {
    // Determine risk status color for labels
    const getStatusStyle = (level) => {
        switch (level) {
            case "Low": return "text-green-600 bg-green-50 border-green-200";
            case "Moderate": return "text-amber-600 bg-amber-50 border-amber-200";
            case "High": return "text-rose-600 bg-rose-50 border-rose-200";
            default: return "text-slate-600 bg-slate-50 border-slate-200";
        }
    };

    return (
        <div
            ref={ref}
            className="p-12 bg-white max-w-[800px] mx-auto text-slate-800 font-sans"
            style={{ position: 'fixed', left: '-9999px', top: '0', zIndex: -1 }} // Hide but keep in DOM for html2canvas
        >
            {/* 1. Header Section */}
            <div className="flex justify-between items-start border-b-2 border-primary-600 pb-8 mb-8">
                <div>
                    <div className="flex items-center gap-2 text-primary-600 mb-2">
                        <HeartPulse size={32} />
                        <span className="text-2xl font-black tracking-tighter uppercase italic">VitaGuard AI</span>
                    </div>
                    <p className="text-xs text-slate-500 font-medium">PREDICTIVE HEALTH ANALYTICS SYSTEM</p>
                </div>
                <div className="text-right">
                    <h2 className="text-3xl font-black text-slate-800 uppercase tracking-tight">Health Analysis Report</h2>
                    <div className="text-sm text-slate-500 mt-2 space-y-1">
                        <p>ID: <span className="font-mono text-slate-700">VG-{Math.random().toString(36).substr(2, 9).toUpperCase()}</span></p>
                        <p>Date: {new Date().toLocaleDateString()}</p>
                        <p>Time: {new Date().toLocaleTimeString()}</p>
                    </div>
                </div>
            </div>

            {/* Disclaimer */}
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 mb-8">
                <div className="flex gap-2 items-center text-amber-600 mb-1">
                    <ShieldAlert size={16} />
                    <span className="text-sm font-bold uppercase tracking-wide">AI-Generated Analysis</span>
                </div>
                <p className="text-xs text-slate-500 leading-relaxed italic">
                    Disclaimer: This report is generated by an artificial intelligence system and provided for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
                </p>
            </div>

            {/* User Profile Summary */}
            <div className="grid grid-cols-2 gap-8 mb-8">
                <div>
                    <h4 className="flex items-center gap-2 text-sm font-black text-slate-400 uppercase tracking-widest mb-4 border-b pb-2">
                        <UserIcon size={14} /> Profile Information
                    </h4>
                    <div className="space-y-2">
                        <p className="text-lg"><strong>Name:</strong> {result.userName}</p>
                        <div className="grid grid-cols-2 gap-4 text-sm">
                            <p><strong>Age:</strong> {formData?.age || 'N/A'}</p>
                            <p><strong>Gender:</strong> {formData?.gender || 'N/A'}</p>
                            <p><strong>Height:</strong> {formData?.height || 'N/A'} cm</p>
                            <p><strong>Weight:</strong> {formData?.weight || 'N/A'} kg</p>
                        </div>
                    </div>
                </div>
                <div>
                    <h4 className="flex items-center gap-2 text-sm font-black text-slate-400 uppercase tracking-widest mb-4 border-b pb-2">
                        <Activity size={14} /> Health Metric
                    </h4>
                    <div className="flex items-center gap-6">
                        <div className="bg-primary-600 text-white p-6 rounded-3xl text-center">
                            <span className="block text-4xl font-black">{result.score}/100</span>
                            <span className="text-[10px] uppercase font-bold tracking-widest opacity-80">Health Risk Score</span>
                        </div>
                        <div>
                            <p className="text-sm text-slate-500 font-bold uppercase mb-1">Risk Category</p>
                            <span className={`px-4 py-1.5 rounded-full text-lg font-black border ${getStatusStyle(result.riskLevel)}`}>
                                {result.riskLevel}
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            {/* 2. Symptoms Section */}
            <div className="mb-8">
                <h4 className="flex items-center gap-2 text-sm font-black text-slate-400 uppercase tracking-widest mb-4 border-b pb-2">
                    <ClipboardCheck size={14} /> Symptoms Provided
                </h4>
                <div className="flex flex-wrap gap-2">
                    {formData?.symptoms?.length > 0 ? (
                        formData.symptoms.map((s, i) => (
                            <span key={i} className="bg-slate-100 text-slate-700 px-3 py-1 rounded-lg text-sm border border-slate-200 font-medium">
                                • {s}
                            </span>
                        ))
                    ) : (
                        <p className="text-slate-400 italic">No specific symptoms reported.</p>
                    )}
                    {formData?.otherSymptoms?.trim() && (
                        <div className="w-full mt-4 p-4 bg-primary-50 rounded-xl border border-primary-100">
                            <p className="text-[10px] font-black uppercase text-primary-600 mb-1 tracking-widest">User Described Symptoms:</p>
                            <p className="text-sm text-slate-700 italic font-medium">"{formData.otherSymptoms}"</p>
                        </div>
                    )}
                </div>
            </div>

            {/* 3. AI Condition Predictions */}
            <div className="mb-8 p-6 border-2 border-slate-100 rounded-3xl">
                <h4 className="flex items-center gap-2 text-sm font-black text-primary-600 uppercase tracking-widest mb-6">
                    <Activity size={14} /> AI Symptom Mapping & Probabilities
                </h4>
                <table className="w-full text-left">
                    <thead>
                        <tr className="text-xs uppercase text-slate-400 border-b">
                            <th className="pb-4 font-black">Possible Indicator</th>
                            <th className="pb-4 font-black">Probability</th>
                            <th className="pb-4 font-black">Risk Level</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-50">
                        {result.details.map((detail, idx) => (
                            <tr key={idx}>
                                <td className="py-4 font-bold text-slate-800 leading-tight">{detail.category} Stress Response<br /><span className="text-[10px] font-medium text-slate-400">Based on clusters of observed metrics</span></td>
                                <td className="py-4 font-mono font-bold text-primary-600">{detail.score}%</td>
                                <td className="py-4"><span className={`px-3 py-1 rounded-lg text-[10px] font-black uppercase border italic ${detail.risk === 'Low' ? 'bg-green-50 text-green-600 border-green-100' : 'bg-amber-50 text-amber-600 border-amber-100'}`}>{detail.risk} Risk</span></td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {/* 4. Risk Assessment Summary */}
            <div className="mb-8 bg-primary-600 text-white p-8 rounded-[2.5rem] shadow-xl">
                <h4 className="text-xs uppercase font-black tracking-[0.2em] mb-4 opacity-70">Official Summary</h4>
                <p className="text-xl font-bold leading-relaxed">
                    Based on your detailed data, you fall under the <span className="underline underline-offset-8">{result.riskLevel} Risk Category</span>.
                    {result.summary}
                </p>
            </div>

            <div className="grid grid-cols-2 gap-8 mb-8">
                {/* 5. Personalized Recommendations */}
                <div className="bg-green-50/50 p-6 rounded-3xl border border-green-100">
                    <h4 className="text-sm font-black text-green-700 uppercase tracking-widest mb-4 flex items-center gap-2">
                        <CheckCircle2 size={16} /> Suggested Actions
                    </h4>
                    <ul className="text-sm space-y-3 text-green-800/80 font-medium">
                        {result.recommendations.map((rec, i) => (
                            <li key={i} className="flex gap-2">• {rec}</li>
                        ))}
                    </ul>
                </div>
                {/* Emergency Warnings */}
                <div className="bg-rose-50 p-6 rounded-3xl border border-rose-100">
                    <h4 className="text-sm font-black text-rose-700 uppercase tracking-widest mb-4 flex items-center gap-2">
                        <ShieldAlert size={16} /> EMERGENCY INDICATORS
                    </h4>
                    <ul className="text-sm space-y-3 text-rose-800/80 font-bold">
                        <li className="flex gap-2">! Difficulty in breathing</li>
                        <li className="flex gap-2">! Severe, crushing chest pain</li>
                        <li className="flex gap-2">! Oxygen levels (SpO2) below 94%</li>
                    </ul>
                </div>
            </div>

            {/* 5. Recommended Dietary Patterns */}
            {result.dietOptions && result.dietOptions.length > 0 && (
                <div className="mb-8 p-6 bg-slate-50 border border-slate-200 rounded-3xl">
                    <h4 className="text-sm font-black text-slate-700 uppercase tracking-widest mb-4 flex items-center gap-2">
                        <span className="text-lg">🥗</span> Recommended Dietary Patterns
                    </h4>
                    <div className="grid grid-cols-2 gap-x-6 gap-y-3">
                        {result.dietOptions.map((diet, i) => (
                            <div key={i} className="flex items-start gap-2 text-sm text-slate-600 font-medium">
                                <span className="text-primary-500 font-black mt-0.5">•</span>
                                <span>{diet}</span>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* 7. Lifestyle & Preventive */}
            <div className="p-6 border-2 border-slate-50 rounded-3xl mb-8">
                <h4 className="text-sm font-black text-slate-400 uppercase tracking-widest mb-4">Lifestyle Optimization</h4>
                <div className="grid grid-cols-3 gap-4">
                    <div className="text-center p-4">
                        <div className="text-2xl mb-1">💤</div>
                        <p className="text-[10px] font-bold text-slate-800 leading-tight uppercase">Sleep Hygiene</p>
                    </div>
                    <div className="text-center p-4">
                        <div className="text-2xl mb-1">🍊</div>
                        <p className="text-[10px] font-bold text-slate-800 leading-tight uppercase">Micronutrients</p>
                    </div>
                    <div className="text-center p-4">
                        <div className="text-2xl mb-1">🌬️</div>
                        <p className="text-[10px] font-bold text-slate-800 leading-tight uppercase">Breathing Tech</p>
                    </div>
                </div>
            </div>

            {/* 8. Daily Health Tips */}
            {result.tips && result.tips.length > 0 && (
                <div className="p-6 bg-amber-50/50 rounded-3xl border border-amber-100 mb-8">
                    <h4 className="text-sm font-black text-amber-700 uppercase tracking-widest mb-4 flex items-center gap-2">
                        💡 Personalized Daily Health Tips
                    </h4>
                    <ul className="text-sm space-y-3 text-amber-800/80 font-medium">
                        {result.tips.map((tip, i) => (
                            <li key={i} className="flex gap-2">✦ {tip}</li>
                        ))}
                    </ul>
                </div>
            )}

            {/* Footer / Page Number */}
            <div className="text-center text-[10px] text-slate-400 uppercase tracking-[0.3em] font-black pt-8 border-t">
                End of VitaGuard Clinical Summary | Page 01 of 01
            </div>
        </div>
    );
});

export default MedicalReportTemplate;
